# Example Workflow (Just Dockerfile Build)

name: CI/CD to Haenu Cluster

on:
  push:
    paths:
      - "api/**"
      - ".github/workflows/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hyeonwoo5342
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: "api/Dockerfile"
          context: ./api
          push: true
          tags: hyeonwoo5342/twitchzzk-api:${{ github.run_number }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: dokdo2013/haenu-cluster
          token: ${{ secrets.GITOPS_TOKEN }}
          path: gitops

      - name: Update deployment tag in GitOps repo
        run: |
          FOLDER_NAME="gitops/apps/haenu"
          APP_NAME="twitchzzk-api"
          cd ${FOLDER_NAME}/${APP_NAME}
          sed -i "s|image: hyeonwoo5342/${APP_NAME}:.*|image: hyeonwoo5342/${APP_NAME}:${{ github.run_number }}|g" deployment.yaml
          git config user.name "dokdo2013"
          git config user.email "hyeonwoo5342@gmail.com"
          git add .
          git commit -m "feat(${APP_NAME}): Build and deploy new commit ${{ github.run_number }}"
          git push
